version: '3.8'
name: immortals
services:

  backend:
    # build: 
    #   context: ../
    #   dockerfile: build/package/Dockerfile
    image: ghcr.io/goldenhand76/immortals:0.0.1
    container_name: backend-Immo

  broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-Immo
    volumes:
      - ../Mosquitto/config/:/mosquitto/config/
      - ../Mosquitto/log/:/mosquitto/log/
      - ../Mosquitto/data:/mosquitto/data/
    ports:
      - "1883:1883"