// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/gRPC/immo/immo.proto
// Protobuf C++ Version: 5.26.1

#include "api/gRPC/immo/immo.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace immo {

inline constexpr SensorResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        topic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SensorResponse::SensorResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SensorResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SensorResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SensorResponseDefaultTypeInternal() {}
  union {
    SensorResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SensorResponseDefaultTypeInternal _SensorResponse_default_instance_;

inline constexpr NodeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NodeRequest::NodeRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NodeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeRequestDefaultTypeInternal() {}
  union {
    NodeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeRequestDefaultTypeInternal _NodeRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR ListRequest::ListRequest(::_pbi::ConstantInitialized) {}
struct ListRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListRequestDefaultTypeInternal() {}
  union {
    ListRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListRequestDefaultTypeInternal _ListRequest_default_instance_;

inline constexpr ActuatorResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        topic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ActuatorResponse::ActuatorResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ActuatorResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActuatorResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActuatorResponseDefaultTypeInternal() {}
  union {
    ActuatorResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActuatorResponseDefaultTypeInternal _ActuatorResponse_default_instance_;

inline constexpr NodeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sensor_{},
        actuator_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NodeResponse::NodeResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NodeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeResponseDefaultTypeInternal() {}
  union {
    NodeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeResponseDefaultTypeInternal _NodeResponse_default_instance_;

inline constexpr ListResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : nodes_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListResponse::ListResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ListResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListResponseDefaultTypeInternal() {}
  union {
    ListResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListResponseDefaultTypeInternal _ListResponse_default_instance_;
}  // namespace immo
static ::_pb::Metadata file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto[6];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_api_2fgRPC_2fimmo_2fimmo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_api_2fgRPC_2fimmo_2fimmo_2eproto = nullptr;
const ::uint32_t
    TableStruct_api_2fgRPC_2fimmo_2fimmo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::immo::NodeRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::immo::NodeRequest, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::immo::NodeRequest, _impl_.address_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::immo::SensorResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::immo::SensorResponse, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::immo::SensorResponse, _impl_.topic_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::immo::ActuatorResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::immo::ActuatorResponse, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::immo::ActuatorResponse, _impl_.topic_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::immo::NodeResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::immo::NodeResponse, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::immo::NodeResponse, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::immo::NodeResponse, _impl_.sensor_),
        PROTOBUF_FIELD_OFFSET(::immo::NodeResponse, _impl_.actuator_),
        PROTOBUF_FIELD_OFFSET(::immo::NodeResponse, _impl_.error_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::immo::ListResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::immo::ListResponse, _impl_.nodes_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::immo::ListRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::immo::NodeRequest)},
        {10, -1, -1, sizeof(::immo::SensorResponse)},
        {20, -1, -1, sizeof(::immo::ActuatorResponse)},
        {30, -1, -1, sizeof(::immo::NodeResponse)},
        {43, -1, -1, sizeof(::immo::ListResponse)},
        {52, -1, -1, sizeof(::immo::ListRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::immo::_NodeRequest_default_instance_._instance,
    &::immo::_SensorResponse_default_instance_._instance,
    &::immo::_ActuatorResponse_default_instance_._instance,
    &::immo::_NodeResponse_default_instance_._instance,
    &::immo::_ListResponse_default_instance_._instance,
    &::immo::_ListRequest_default_instance_._instance,
};
const char descriptor_table_protodef_api_2fgRPC_2fimmo_2fimmo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030api/gRPC/immo/immo.proto\022\004immo\",\n\013Node"
    "Request\022\014\n\004name\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\"-"
    "\n\016SensorResponse\022\014\n\004name\030\001 \001(\t\022\r\n\005topic\030"
    "\002 \001(\t\"/\n\020ActuatorResponse\022\014\n\004name\030\001 \001(\t\022"
    "\r\n\005topic\030\002 \001(\t\"\207\001\n\014NodeResponse\022\014\n\004name\030"
    "\001 \001(\t\022\n\n\002id\030\002 \001(\t\022$\n\006sensor\030\003 \003(\0132\024.immo"
    ".SensorResponse\022(\n\010actuator\030\004 \003(\0132\026.immo"
    ".ActuatorResponse\022\r\n\005error\030\005 \001(\t\"1\n\014List"
    "Response\022!\n\005nodes\030\001 \003(\0132\022.immo.NodeRespo"
    "nse\"\r\n\013ListRequest2\252\001\n\013ImmoService\0225\n\014Di"
    "scoverNode\022\021.immo.NodeRequest\032\022.immo.Nod"
    "eResponse\0220\n\007AddNode\022\021.immo.NodeRequest\032"
    "\022.immo.NodeResponse\0222\n\tListNodes\022\021.immo."
    "ListRequest\032\022.immo.ListResponseB\010Z\006./imm"
    "ob\006proto3"
};
static ::absl::once_flag descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto = {
    false,
    false,
    569,
    descriptor_table_protodef_api_2fgRPC_2fimmo_2fimmo_2eproto,
    "api/gRPC/immo/immo.proto",
    &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_api_2fgRPC_2fimmo_2fimmo_2eproto::offsets,
    file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto,
    file_level_enum_descriptors_api_2fgRPC_2fimmo_2fimmo_2eproto,
    file_level_service_descriptors_api_2fgRPC_2fimmo_2fimmo_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_getter() {
  return &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto;
}
namespace immo {
// ===================================================================

class NodeRequest::_Internal {
 public:
};

NodeRequest::NodeRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:immo.NodeRequest)
}
inline PROTOBUF_NDEBUG_INLINE NodeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        address_(arena, from.address_),
        _cached_size_{0} {}

NodeRequest::NodeRequest(
    ::google::protobuf::Arena* arena,
    const NodeRequest& from)
    : ::google::protobuf::Message(arena) {
  NodeRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:immo.NodeRequest)
}
inline PROTOBUF_NDEBUG_INLINE NodeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        address_(arena),
        _cached_size_{0} {}

inline void NodeRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NodeRequest::~NodeRequest() {
  // @@protoc_insertion_point(destructor:immo.NodeRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NodeRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.address_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NodeRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(NodeRequest, _impl_._cached_size_),
              false,
          },
          &NodeRequest::MergeImpl,
          &NodeRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void NodeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:immo.NodeRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.address_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* NodeRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2> NodeRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NodeRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::immo::NodeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string address = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NodeRequest, _impl_.address_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NodeRequest, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(NodeRequest, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string address = 2;
    {PROTOBUF_FIELD_OFFSET(NodeRequest, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\4\7\0\0\0\0\0"
    "immo.NodeRequest"
    "name"
    "address"
  }},
};

::uint8_t* NodeRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:immo.NodeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.NodeRequest.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string address = 2;
  if (!this->_internal_address().empty()) {
    const std::string& _s = this->_internal_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.NodeRequest.address");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:immo.NodeRequest)
  return target;
}

::size_t NodeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:immo.NodeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string address = 2;
  if (!this->_internal_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_address());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NodeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NodeRequest*>(&to_msg);
  auto& from = static_cast<const NodeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:immo.NodeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NodeRequest::CopyFrom(const NodeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:immo.NodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NodeRequest::IsInitialized() const {
  return true;
}

void NodeRequest::InternalSwap(NodeRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
}

::google::protobuf::Metadata NodeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_getter,
                                   &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once,
                                   file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto[0]);
}
// ===================================================================

class SensorResponse::_Internal {
 public:
};

SensorResponse::SensorResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:immo.SensorResponse)
}
inline PROTOBUF_NDEBUG_INLINE SensorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        topic_(arena, from.topic_),
        _cached_size_{0} {}

SensorResponse::SensorResponse(
    ::google::protobuf::Arena* arena,
    const SensorResponse& from)
    : ::google::protobuf::Message(arena) {
  SensorResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:immo.SensorResponse)
}
inline PROTOBUF_NDEBUG_INLINE SensorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        topic_(arena),
        _cached_size_{0} {}

inline void SensorResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SensorResponse::~SensorResponse() {
  // @@protoc_insertion_point(destructor:immo.SensorResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SensorResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.topic_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SensorResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(SensorResponse, _impl_._cached_size_),
              false,
          },
          &SensorResponse::MergeImpl,
          &SensorResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void SensorResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:immo.SensorResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.topic_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SensorResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 37, 2> SensorResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SensorResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::immo::SensorResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string topic = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SensorResponse, _impl_.topic_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SensorResponse, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(SensorResponse, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string topic = 2;
    {PROTOBUF_FIELD_OFFSET(SensorResponse, _impl_.topic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\4\5\0\0\0\0\0"
    "immo.SensorResponse"
    "name"
    "topic"
  }},
};

::uint8_t* SensorResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:immo.SensorResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.SensorResponse.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string topic = 2;
  if (!this->_internal_topic().empty()) {
    const std::string& _s = this->_internal_topic();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.SensorResponse.topic");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:immo.SensorResponse)
  return target;
}

::size_t SensorResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:immo.SensorResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string topic = 2;
  if (!this->_internal_topic().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_topic());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SensorResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SensorResponse*>(&to_msg);
  auto& from = static_cast<const SensorResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:immo.SensorResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_topic().empty()) {
    _this->_internal_set_topic(from._internal_topic());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SensorResponse::CopyFrom(const SensorResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:immo.SensorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SensorResponse::IsInitialized() const {
  return true;
}

void SensorResponse::InternalSwap(SensorResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.topic_, &other->_impl_.topic_, arena);
}

::google::protobuf::Metadata SensorResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_getter,
                                   &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once,
                                   file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto[1]);
}
// ===================================================================

class ActuatorResponse::_Internal {
 public:
};

ActuatorResponse::ActuatorResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:immo.ActuatorResponse)
}
inline PROTOBUF_NDEBUG_INLINE ActuatorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        topic_(arena, from.topic_),
        _cached_size_{0} {}

ActuatorResponse::ActuatorResponse(
    ::google::protobuf::Arena* arena,
    const ActuatorResponse& from)
    : ::google::protobuf::Message(arena) {
  ActuatorResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:immo.ActuatorResponse)
}
inline PROTOBUF_NDEBUG_INLINE ActuatorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        topic_(arena),
        _cached_size_{0} {}

inline void ActuatorResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ActuatorResponse::~ActuatorResponse() {
  // @@protoc_insertion_point(destructor:immo.ActuatorResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ActuatorResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.topic_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ActuatorResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ActuatorResponse, _impl_._cached_size_),
              false,
          },
          &ActuatorResponse::MergeImpl,
          &ActuatorResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ActuatorResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:immo.ActuatorResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.topic_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ActuatorResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> ActuatorResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ActuatorResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::immo::ActuatorResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string topic = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ActuatorResponse, _impl_.topic_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ActuatorResponse, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(ActuatorResponse, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string topic = 2;
    {PROTOBUF_FIELD_OFFSET(ActuatorResponse, _impl_.topic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\4\5\0\0\0\0\0"
    "immo.ActuatorResponse"
    "name"
    "topic"
  }},
};

::uint8_t* ActuatorResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:immo.ActuatorResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.ActuatorResponse.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string topic = 2;
  if (!this->_internal_topic().empty()) {
    const std::string& _s = this->_internal_topic();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.ActuatorResponse.topic");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:immo.ActuatorResponse)
  return target;
}

::size_t ActuatorResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:immo.ActuatorResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string topic = 2;
  if (!this->_internal_topic().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_topic());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ActuatorResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ActuatorResponse*>(&to_msg);
  auto& from = static_cast<const ActuatorResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:immo.ActuatorResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_topic().empty()) {
    _this->_internal_set_topic(from._internal_topic());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ActuatorResponse::CopyFrom(const ActuatorResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:immo.ActuatorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ActuatorResponse::IsInitialized() const {
  return true;
}

void ActuatorResponse::InternalSwap(ActuatorResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.topic_, &other->_impl_.topic_, arena);
}

::google::protobuf::Metadata ActuatorResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_getter,
                                   &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once,
                                   file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto[2]);
}
// ===================================================================

class NodeResponse::_Internal {
 public:
};

NodeResponse::NodeResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:immo.NodeResponse)
}
inline PROTOBUF_NDEBUG_INLINE NodeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : sensor_{visibility, arena, from.sensor_},
        actuator_{visibility, arena, from.actuator_},
        name_(arena, from.name_),
        id_(arena, from.id_),
        error_(arena, from.error_),
        _cached_size_{0} {}

NodeResponse::NodeResponse(
    ::google::protobuf::Arena* arena,
    const NodeResponse& from)
    : ::google::protobuf::Message(arena) {
  NodeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:immo.NodeResponse)
}
inline PROTOBUF_NDEBUG_INLINE NodeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : sensor_{visibility, arena},
        actuator_{visibility, arena},
        name_(arena),
        id_(arena),
        error_(arena),
        _cached_size_{0} {}

inline void NodeResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NodeResponse::~NodeResponse() {
  // @@protoc_insertion_point(destructor:immo.NodeResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NodeResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.id_.Destroy();
  _impl_.error_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NodeResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_._cached_size_),
              false,
          },
          &NodeResponse::MergeImpl,
          &NodeResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void NodeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:immo.NodeResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sensor_.Clear();
  _impl_.actuator_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.id_.ClearToEmpty();
  _impl_.error_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* NodeResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 37, 2> NodeResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_NodeResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::immo::NodeResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.name_)}},
    // string id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.id_)}},
    // repeated .immo.SensorResponse sensor = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.sensor_)}},
    // repeated .immo.ActuatorResponse actuator = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 1, PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.actuator_)}},
    // string error = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.error_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string id = 2;
    {PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .immo.SensorResponse sensor = 3;
    {PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.sensor_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .immo.ActuatorResponse actuator = 4;
    {PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.actuator_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string error = 5;
    {PROTOBUF_FIELD_OFFSET(NodeResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::immo::SensorResponse>()},
    {::_pbi::TcParser::GetTable<::immo::ActuatorResponse>()},
  }}, {{
    "\21\4\2\0\0\5\0\0"
    "immo.NodeResponse"
    "name"
    "id"
    "error"
  }},
};

::uint8_t* NodeResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:immo.NodeResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.NodeResponse.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string id = 2;
  if (!this->_internal_id().empty()) {
    const std::string& _s = this->_internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.NodeResponse.id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // repeated .immo.SensorResponse sensor = 3;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_sensor_size());
       i < n; i++) {
    const auto& repfield = this->_internal_sensor().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            3, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // repeated .immo.ActuatorResponse actuator = 4;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_actuator_size());
       i < n; i++) {
    const auto& repfield = this->_internal_actuator().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            4, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // string error = 5;
  if (!this->_internal_error().empty()) {
    const std::string& _s = this->_internal_error();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "immo.NodeResponse.error");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:immo.NodeResponse)
  return target;
}

::size_t NodeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:immo.NodeResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .immo.SensorResponse sensor = 3;
  total_size += 1UL * this->_internal_sensor_size();
  for (const auto& msg : this->_internal_sensor()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .immo.ActuatorResponse actuator = 4;
  total_size += 1UL * this->_internal_actuator_size();
  for (const auto& msg : this->_internal_actuator()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string id = 2;
  if (!this->_internal_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_id());
  }

  // string error = 5;
  if (!this->_internal_error().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NodeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NodeResponse*>(&to_msg);
  auto& from = static_cast<const NodeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:immo.NodeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_sensor()->MergeFrom(
      from._internal_sensor());
  _this->_internal_mutable_actuator()->MergeFrom(
      from._internal_actuator());
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NodeResponse::CopyFrom(const NodeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:immo.NodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NodeResponse::IsInitialized() const {
  return true;
}

void NodeResponse::InternalSwap(NodeResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.sensor_.InternalSwap(&other->_impl_.sensor_);
  _impl_.actuator_.InternalSwap(&other->_impl_.actuator_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_, &other->_impl_.error_, arena);
}

::google::protobuf::Metadata NodeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_getter,
                                   &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once,
                                   file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto[3]);
}
// ===================================================================

class ListResponse::_Internal {
 public:
};

ListResponse::ListResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:immo.ListResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : nodes_{visibility, arena, from.nodes_},
        _cached_size_{0} {}

ListResponse::ListResponse(
    ::google::protobuf::Arena* arena,
    const ListResponse& from)
    : ::google::protobuf::Message(arena) {
  ListResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:immo.ListResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : nodes_{visibility, arena},
        _cached_size_{0} {}

inline void ListResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListResponse::~ListResponse() {
  // @@protoc_insertion_point(destructor:immo.ListResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ListResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ListResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(ListResponse, _impl_._cached_size_),
              false,
          },
          &ListResponse::MergeImpl,
          &ListResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void ListResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:immo.ListResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nodes_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ListResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ListResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ListResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::immo::ListResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .immo.NodeResponse nodes = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListResponse, _impl_.nodes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .immo.NodeResponse nodes = 1;
    {PROTOBUF_FIELD_OFFSET(ListResponse, _impl_.nodes_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::immo::NodeResponse>()},
  }}, {{
  }},
};

::uint8_t* ListResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:immo.ListResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .immo.NodeResponse nodes = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_nodes_size());
       i < n; i++) {
    const auto& repfield = this->_internal_nodes().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:immo.ListResponse)
  return target;
}

::size_t ListResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:immo.ListResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .immo.NodeResponse nodes = 1;
  total_size += 1UL * this->_internal_nodes_size();
  for (const auto& msg : this->_internal_nodes()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ListResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListResponse*>(&to_msg);
  auto& from = static_cast<const ListResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:immo.ListResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_nodes()->MergeFrom(
      from._internal_nodes());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListResponse::CopyFrom(const ListResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:immo.ListResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ListResponse::IsInitialized() const {
  return true;
}

void ListResponse::InternalSwap(ListResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.nodes_.InternalSwap(&other->_impl_.nodes_);
}

::google::protobuf::Metadata ListResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_getter,
                                   &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once,
                                   file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto[4]);
}
// ===================================================================

class ListRequest::_Internal {
 public:
};

ListRequest::ListRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:immo.ListRequest)
}
ListRequest::ListRequest(
    ::google::protobuf::Arena* arena,
    const ListRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  ListRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:immo.ListRequest)
}









::google::protobuf::Metadata ListRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_getter,
                                   &descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto_once,
                                   file_level_metadata_api_2fgRPC_2fimmo_2fimmo_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace immo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_api_2fgRPC_2fimmo_2fimmo_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
