// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type Actuators struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Topic     sql.NullString `json:"topic"`
	NodeID    int64          `json:"node_id"`
	CreatedAt time.Time      `json:"created_at"`
}

type Nodes struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	AgentID   sql.NullInt32  `json:"agent_id"`
	ClientID  sql.NullString `json:"client_id"`
	IsOnline  sql.NullBool   `json:"is_online"`
	CreatedAt time.Time      `json:"created_at"`
}

type Sensors struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Topic     sql.NullString `json:"topic"`
	NodeID    int64          `json:"node_id"`
	CreatedAt time.Time      `json:"created_at"`
}
